### ISSUE TITLE
Move CLI into own repo

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther-analysis#22]
## Background

To better focus this repository on analysis, we should break out the CLI code into its own repo, and then install it with `pip` here.

## To-do

- [ ]  New repo for the CLI
- [ ]  Publish to pip
- [ ]  Add the new pip package to CI in this repo
